### ISSUE TITLE
Receiving undefined route

### ISSUE THREAD

**Issue by jnatherley** [nutgaard/react-router-breadcrumbs#40] opened 2016-05-19 12:20 UTC
```
 Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    at createText (webpack:///./~/react-router-breadcrumbs/dist/breadcrumbs.js?:61:69)
```

My code

```
<Route name="Instances" onEnter={requireLogin} path="instances">
          <IndexRoute name="Instances" component={InstancesPage}/>
          <Route breadcrumbIgnore name="NewInstance" path="new" component={NewInstancePage}/>
          <Route breadcrumbIgnore name="NewInstancePage" breadcrumbName=":id" path=":id" component={InstancePage}/>
        </Route>
```

```
<Breadcrumbs 
                wrappingComponent="div"
                routes={routes}
                createSeparator=" | "/>
```

**Comment by nutgaard** [comment] 2016-05-19 14:21
Hi, thanks for reporting issues. :)

From what I understand it is caused by this line 
`const text = route.breadcrumbName || route.name || route.component.name;` [from here](https://github.com/nutgaard/react-router-breadcrumbs/blob/master/src/breadcrumbs.js#L19)

It seems like it is the main which causes this `<Route name="Instances" ...`, and that `route.component` is `undefined` and thus causing the `Cannot read property of undefined`.

At first glance this seems like an bug, as it should have shortcircuited on `route.name`. 

I'll try to replicate the error after work, and get back to you.

**Comment by nutgaard** [comment] 2016-05-19 14:22
If you find a workaround, or find a way to solve it dont hesitate to submit a PR. 

All contributions are welcome.

**Comment by nutgaard** [comment] 2016-05-19 15:36
Tried to recreate this issue here: https://github.com/nutgaard/react-router-breadcrumbs/commit/ae148f25303baf77356c0c18a267adc39e228f18

But could not recreate the issue as you described. Could you post what `routes` are when this happend? E.g `JSON.stringify(routes)` at the start of the render method which create the breadcrumbs

**Comment by jnatherley** [comment] 2016-05-20 10:46
```
<Route name="Main" component={Main}>
      <Route path="/" onEnter={requireLogin} component={App}>
        <IndexRoute name="Dashboard" onEnter={requireLogin} component={Dashboard}/>
        <Route name="Dashboard" onEnter={requireLogin} path="dashboard" component={Dashboard}/>

        <Route name="Nodes" onEnter={requireLogin} path="nodes">
          <IndexRoute name="Nodes" component={NodesPage}/>
          <Route onEnter={requireLogin} name="NodePage" breadcrumbName=":id" path=":id" component={NodePage}>
            <IndexRoute component={NodeCPUPage}/>
            <Route name="CPU" path="cpu" component={NodeCPUPage}/>
            <Route name="Network" path="network" component={NodeCPUPage}/>
            <Route name="Instances" path="instances" component={NodeInstancesPage}/>
            <Route name="Storage" path="storage" component={NodeStoragePage}/>
          </Route>
        </Route>

        <Route name="Resource Groups" onEnter={requireLogin} path="resource_groups">
          <IndexRoute name="Resource Groups" component={ResourceGroups}/>
          <Route onEnter={requireLogin} name="ResourceGroupPage" path=":id" breadcrumbName=":id" component={ResourceGroupPage}>
            <IndexRoute name="Storage" component={ResourceGroupStoragePage}/>
            <Route name="Storage" path="storage" component={ResourceGroupStoragePage}/>
          </Route>
        </Route>

        <Route name="Networks" onEnter={requireLogin} path="networks" component={Networks}>
          <IndexRoute name="Networks" components={{NetworksHeader, NetworkListPage}}/>
          <Route breadcrumbIgnore path="list" components={{NetworksHeader, NetworkListPage}}/>
          <Route breadcrumbIgnore path="manage" components={{NetworksHeader, NetworkManager}}/>
          <Route breadcrumbIgnore path=":id" component={NetworkDetailsPage}/>
        </Route>

        <Route name="Instances" onEnter={requireLogin} path="instances">
          <IndexRoute name="Instances" component={InstancesPage}/>
          <Route breadcrumbIgnore name="NewInstance" path="new" component={NewInstancePage}/>
          <Route breadcrumbIgnore name="NewInstancePage" breadcrumbName=":id" path=":id" component={InstancePage}/>
        </Route>

      </Route>
      
      <Route breadcrumbIgnore name="login"  path="login" component={Login}/>
      <Route breadcrumbIgnore name="logout" path="logout" onEnter={logout}/>
    </Route>
```

Tried removing the Network block just incase that was causing the error. Here is the JSON:

```
[
   {

   },
   {
      "name":"Main",
      "childRoutes":[
         {
            "path":"/",
            "indexRoute":{
               "name":"Dashboard"
            },
            "childRoutes":[
               {
                  "name":"Dashboard",
                  "path":"dashboard"
               },
               {
                  "name":"Nodes",
                  "path":"nodes",
                  "indexRoute":{
                     "name":"Nodes"
                  },
                  "childRoutes":[
                     {
                        "name":"NodePage",
                        "breadcrumbName":":id",
                        "path":":id",
                        "indexRoute":{

                        },
                        "childRoutes":[
                           {
                              "name":"CPU",
                              "path":"cpu"
                           },
                           {
                              "name":"Network",
                              "path":"network"
                           },
                           {
                              "name":"Instances",
                              "path":"instances"
                           },
                           {
                              "name":"Storage",
                              "path":"storage"
                           }
                        ]
                     }
                  ]
               },
               {
                  "name":"Resource Groups",
                  "path":"resource_groups",
                  "indexRoute":{
                     "name":"Resource Groups"
                  },
                  "childRoutes":[
                     {
                        "name":"ResourceGroupPage",
                        "path":":id",
                        "breadcrumbName":":id",
                        "indexRoute":{
                           "name":"Storage"
                        },
                        "childRoutes":[
                           {
                              "name":"Storage",
                              "path":"storage"
                           }
                        ]
                     }
                  ]
               },
               {
                  "name":"Networks",
                  "path":"networks",
                  "indexRoute":{
                     "name":"Networks",
                     "components":{

                     }
                  },
                  "childRoutes":[
                     {
                        "breadcrumbIgnore":true,
                        "path":"list",
                        "components":{

                        }
                     },
                     {
                        "breadcrumbIgnore":true,
                        "path":"manage",
                        "components":{

                        }
                     },
                     {
                        "breadcrumbIgnore":true,
                        "path":":id"
                     }
                  ]
               },
               {
                  "name":"Instances",
                  "path":"instances",
                  "indexRoute":{
                     "name":"Instances"
                  },
                  "childRoutes":[
                     {
                        "breadcrumbIgnore":true,
                        "name":"NewInstance",
                        "path":"new"
                     },
                     {
                        "breadcrumbIgnore":true,
                        "name":"NewInstancePage",
                        "breadcrumbName":":id",
                        "path":":id"
                     }
                  ]
               }
            ]
         },
         {
            "breadcrumbIgnore":true,
            "name":"login",
            "path":"login"
         },
         {
            "breadcrumbIgnore":true,
            "name":"logout",
            "path":"logout"
         }
      ]
   },
   {
      "path":"/",
      "indexRoute":{
         "name":"Dashboard"
      },
      "childRoutes":[
         {
            "name":"Dashboard",
            "path":"dashboard"
         },
         {
            "name":"Nodes",
            "path":"nodes",
            "indexRoute":{
               "name":"Nodes"
            },
            "childRoutes":[
               {
                  "name":"NodePage",
                  "breadcrumbName":":id",
                  "path":":id",
                  "indexRoute":{

                  },
                  "childRoutes":[
                     {
                        "name":"CPU",
                        "path":"cpu"
                     },
                     {
                        "name":"Network",
                        "path":"network"
                     },
                     {
                        "name":"Instances",
                        "path":"instances"
                     },
                     {
                        "name":"Storage",
                        "path":"storage"
                     }
                  ]
               }
            ]
         },
         {
            "name":"Resource Groups",
            "path":"resource_groups",
            "indexRoute":{
               "name":"Resource Groups"
            },
            "childRoutes":[
               {
                  "name":"ResourceGroupPage",
                  "path":":id",
                  "breadcrumbName":":id",
                  "indexRoute":{
                     "name":"Storage"
                  },
                  "childRoutes":[
                     {
                        "name":"Storage",
                        "path":"storage"
                     }
                  ]
               }
            ]
         },
         {
            "name":"Networks",
            "path":"networks",
            "indexRoute":{
               "name":"Networks",
               "components":{

               }
            },
            "childRoutes":[
               {
                  "breadcrumbIgnore":true,
                  "path":"list",
                  "components":{

                  }
               },
               {
                  "breadcrumbIgnore":true,
                  "path":"manage",
                  "components":{

                  }
               },
               {
                  "breadcrumbIgnore":true,
                  "path":":id"
               }
            ]
         },
         {
            "name":"Instances",
            "path":"instances",
            "indexRoute":{
               "name":"Instances"
            },
            "childRoutes":[
               {
                  "breadcrumbIgnore":true,
                  "name":"NewInstance",
                  "path":"new"
               },
               {
                  "breadcrumbIgnore":true,
                  "name":"NewInstancePage",
                  "breadcrumbName":":id",
                  "path":":id"
               }
            ]
         }
      ]
   },
   {
      "name":"Dashboard",
      "path":"dashboard"
   }
]
```

**Comment by jnatherley** [comment] 2016-05-20 10:48
Thanks for your help :)

It manages to render for react-breadcrumbs the other library you mentioned in the docs.

**Comment by nutgaard** [comment] 2016-05-20 13:03
Thanks for posting the route-config, if I find the bug in my code I'll let you know.

Its great if react-breadcrumbs fits your usecase.

**Comment by jnatherley** [comment] 2016-05-23 11:01
I also had some issues with that library also, besides i like more of the options provided here. Let me know if you manage to find a solution!

**Comment by nutgaard** [comment] 2016-07-01 13:00
I've looking a bit into this now. And the only thing I can see which could indicate this error is the empty object at the start of the `routes`-array. I've looked at some other setups I have with react-router, and none of them have this empty object at the start.

Any idea where it might come from?

**Comment by nutgaard** [comment] 2016-08-12 18:38
I've not been able to reproduce this issue with any kind of route-setup locally. Closing it for now, but dont hesitate to comment if this still is an issue for you.

**Closed by nutgaard** 2016-08-12 18:38 UTC
Labels: bug, not reproducable, wontfix

**Comment by ruoptic** [comment] 2016-10-24 18:01
Hi, I've got this issue too. I see that attributes we give to component are stored in another properties, e.g.
`route.props.name` or `route.props.breadcrumbName`. And this is the way, we are trying to get this values in _react-router-breadcrumbs_:  
`var text = route.breadcrumbName || route.name || route.component.name;`

**Comment by nutgaard** [comment] 2016-10-24 18:53
Hi,
could you open a separate issue, as this is most likely not related. 

Please include an excerpt of what you are passing in as `routes` and what version of the library and react-router you are using. :)
