### ISSUE TITLE
Can't use breadcrumbs if it's rendered using RouterContext (Server Side Rendering)

### ISSUE THREAD

**Issue by Nicarim** [nutgaard/react-router-breadcrumbs#173] opened 2016-10-07 10:42 UTC
As the title says, it's impossible for me to use breadcrumbs if components are generated using RouterContext, that happens whenever it's rendered by the server. 

```
TypeError: Cannot read property 'name' of undefined
      at createText (C:\_Projects\kolomnie-frontend\node_modules\react-router-breadcrumbs\dist\breadcrumbs.js:61:69)
      at C:\_Projects\kolomnie-frontend\node_modules\react-router-breadcrumbs\dist\breadcrumbs.js:86:20
      at Array.map (native)
      at renderCrumbs (C:\_Projects\kolomnie-frontend\node_modules\react-router-breadcrumbs\dist\breadcrumbs.js:103:41)
      at Breadcrumbs (C:\_Projects\kolomnie-frontend\node_modules\react-router-breadcrumbs\dist\breadcrumbs.js:114:18)
      at ReactCompositeComponentWrapper._constructComponentWithoutOwner (C:\_Projects\kolomnie-frontend\node_modules\react\lib\ReactCompositeComponent.js:310:27)
      at ReactCompositeComponentWrapper._constructComponent (C:\_Projects\kolomnie-frontend\node_modules\react\lib\ReactCompositeComponent.js:278:21)
      at ReactCompositeComponentWrapper.mountComponent (C:\_Projects\kolomnie-frontend\node_modules\react\lib\ReactCompositeComponent.js:190:21)
      at Object.mountComponent (C:\_Projects\kolomnie-frontend\node_modules\react\lib\ReactReconciler.js:47:35)
      at ReactCompositeComponentWrapper.performInitialMount (C:\_Projects\kolomnie-frontend\node_modules\react\lib\ReactCompositeComponent.js:385:34)
      at ReactCompositeComponentWrapper.mountComponent (C:\_Projects\kolomnie-frontend\node_modules\react\lib\ReactCompositeComponent.js:260:21)
      at Object.mountComponent (C:\_Projects\kolomnie-frontend\node_modules\react\lib\ReactReconciler.js:47:35)
      at ReactDOMComponent.mountChildren (C:\_Projects\kolomnie-frontend\node_modules\react\lib\ReactMultiChild.js:240:44)
      at ReactDOMComponent._createContentMarkup (C:\_Projects\kolomnie-frontend\node_modules\react\lib\ReactDOMComponent.js:660:32)
      at ReactDOMComponent.mountComponent (C:\_Projects\kolomnie-frontend\node_modules\react\lib\ReactDOMComponent.js:527:29)
      at Object.mountComponent (C:\_Projects\kolomnie-frontend\node_modules\react\lib\ReactReconciler.js:47:35) ]
```

I've investigated that, and it appears to happend because RouterContext becomes top-level component, which Breadcrumbs try to get name of, and since that property doesn't exist , it throws an error, here is dump of `route` variable in `createText (C:\_Projects\kolomnie-frontend\node_modules\react-router-breadcrumbs\dist\breadcrumbs.js:61:69)`

```
{ render: [Function: render],
  history: undefined,
  childRoutes:
   [ { name: 'Główna',
       path: '/',
       component: [Object],
       indexRoute: [Object],
       childRoutes: [Object] } ] }
```

How Can I overcome that? Is that a bug? Or am I doing something wrong?

**Comment by nutgaard** [comment] 2016-10-07 12:56
Hi,
the reason for this is rather simple; this modules haven't been prepped for server side rendering yet. So you are not doing anything wrong, as this is a missing feature at the moment.

A temporary quickfix could be to slice away the top-level component before passing `routes` to the component. Alternatively you could add `breadcrumbName` or `name` to the top-level and thereby short circuiting the `createText` function so that it doesnt try to get the `name´-property of `route.component`. Both these fixes has the unfortunate consequence of have custom server side code, something that should be avoided. So I will look into making a permanent fix for this within the module.

**Comment by Nicarim** [comment] 2016-10-07 12:59
Hey, thanks for quick reply and the comment. For now I've just made a temprorary fix for that as you said - by removing the top level component, but that's something that shouldn't be happening, so I'm looking forward to your fix whenever it comes - no hurry.

**Comment by nutgaard** [comment] 2016-11-04 12:08
Hey again. 
Had some time to investigate this issue today. But were unable to reproduce the behaviour you mentioned (e.g. RouterContext becoming the top-level component).

I'm not sure what kind of setup you have, but feel free to compare it to the setup here; https://github.com/nutgaard/react-router-breadcrumbs/commit/ebbc7888ae9dc7cdffba9bcd7c8404a742adfcd4

Its a simple serverside setup with express server. If you want to run it locally just start it with `node serverside.js`

**Comment by jasonnathan** [comment] 2016-11-09 04:45
I've had no issues using this with ssr. However, I did get the error mentioned when at least one of my routes did not have a `name` defined. I also had to define `breadcrumbIgnore` on the root `App` component

**Comment by nutgaard** [comment] 2016-11-09 19:53
Closing this issue as it was not reproducible, and no more information has been given. 

@Nicarim If you got anymore information regarding this issue please post it so that I can look into it more closely.

@jasonnathan Nice to hear you had no issues with ssr. If you feel like the missing `name` or need for `breadcrumbIgnore` is a bug please report it alongside your router-setup so that I can take a look at it. A goal of this library is to provide a easy initial setup, and at the same time provide extention-point for changing the behavior to your specific needs.

**Closed by nutgaard** 2016-11-09 19:53 UTC
Labels: not reproducible
